// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FailTrack.Models;

public partial class Lines
{
    public int Id { get; set; }

    public string LineName { get; set; }

    public virtual ICollection<Machines> Machines { get; set; } = new List<Machines>();

    public virtual ICollection<Maintenance> Maintenance { get; set; } = new List<Maintenance>();

    public virtual ICollection<Tooling> Tooling { get; set; } = new List<Tooling>();

    public virtual ICollection<Users> Users { get; set; } = new List<Users>();
}