// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FailTrack.Models;

public partial class Machines
{
    public int Id { get; set; }

    public int? IdLine { get; set; }

    public string MachineName { get; set; }

    public virtual Lines IdLineNavigation { get; set; }

    public virtual ICollection<Maintenance> Maintenance { get; set; } = new List<Maintenance>();
}